envs:
  DGLBACKEND: pytorch

resources:
  # accelerators: K80:1

workdir: .

file_mounts:
  /hello-s3:
    name: hello-s3-na
    source: data
    store: s3
    mode: MOUNT

setup: |
  echo "*** setup"

  uv venv
  source .venv/bin/activate

  uv pip install -r requirements.txt

run: |
  echo "*** run"

  uv run train.py
